# L'inférence causale {.tabset}

Une grande partie des sciences sociales porte sur la causalité. On peut se demander si [l'inscription des électeurs augmente la participation politique](https://egap.org/resource/electoral-administration-in-kenya/), si [la responsabilisation bottom-up peut améliorer les perspectives en matière de santé](https://egap.org/resource/does-bottom-up-accountability-work-evidence-from-uganda/), ou si [les récits personnels des migrants aident à réduire les attitudes préjudiciables à leur égard](https://egap.org/resource/brief-70-how-personal-narratives-reduce-negative-attitudes-towards-immigrants-in-kenya/).

Au cours de la dernière décennie, les sciences sociales sont devenues beaucoup plus strictes quant à la formulation des assertions de causalité, en s'appuyant sur une longue histoire de travaux sur la causalité remontant aux classiques de [Fisher and Rubin](#causalinference-classics). On recourt davantage aux expériences; la randomisation est devenue la norme de référence pour répondre aux questions causales.

Dans ce module, nous introduisons l'approche contrefactuelle de l'inférence causale et comment des affirmations basées sur des assertions de causalité peuvent être interprétées. Nous présentons le modèle à résultats potentiels et la manière dont l'assignation aléatoire nous aide à faire des assertions sur ce qui se serait passé en l'absence de la politique publique, de l'action ou du programme que nous étudions. Nous discutons des trois hypothèses de base pour l'inférence causale : l'assignation aléatoire des sujets au traitement, la non-interférence et l'excluabilité.

## Contenu

 - Qu'entendons-nous par **"cause"**? Et pourquoi est-il important d'être clair sur le sens des assertions de causalité?

 - Une introduction aux **résultats potentiels** comme une façon de penser aux états contrefactuels du monde.

 - La **randomisation** nous aide à comprendre les assertions causales contrefactuelles d'une manière particulièrement utile.

 - Les trois principales **hypothèses de base** pour l'inférence causale: l'assignation aléatoire des sujets au traitement, la non-interférence et l'excluabilité.

 - Comparaison des études aléatoires avec des études d'observation.

 - La randomisation apporte une validité interne élevée, mais elle ne peut pas assurer la **validité externe**.

 - Votre question causale est liée à votre[design de recherche](the-research-design-process.html).

## Slides

Vous trouverez ci-dessous des slides avec le contenu de base de notre conférence sur la causalité. Vous pouvez les utiliser directement ou les copier localement avant de les éditer.

- [Code source en R Markdown](https://egap.github.io/learningdays-resources/Slides/causalinference-slides.Rmd)

- [Version PDF](https://egap.github.io/learningdays-resources/Slides/causalinference-slides.pdf)

- [Version HTML](https://egap.github.io/learningdays-resources/Slides/causalinference-slides.html)

Vous pouvez aussi lire les slides des précédents EGAP Learning Days:

 - [La présentation de l'inférence causale aux EGAP Learning Days à l'African School of Economics, Abomey-Calavi, juin 2019](https://egap.github.io/learningdays-resources/Slides/Examples/causality-benin.pdf)

 - [La présentation de l'inférence causale aux EGAP Learning Days à l'Université des Andes, Bogotá, avril 2019](https://egap.github.io/learningdays-resources/Slides/Examples/causality-bogota.pdf)

 - [La présentation de l'inférence causale aux EGAP Learning Days à l'Université catholique d'Uruguay, Montevideo, mars 2018](https://egap.github.io/learningdays-resources/Slides/Examples/causality-montevideo.pdf)

 - [La présentation de l'inférence causale aux EGAP Learning Days à Guatemala City, Guatemala, août 2017](https://egap.github.io/learningdays-resources/Slides/Examples/causality-guatemala.pdf)

 - [La présentation à l'introduction sur les expériences aux EGAP Learning Days à Guatemala City, Guatemala, août 2017](https://egap.github.io/learningdays-resources/Slides/Examples/intro_experiments-guatemala.pdf)

 - [La présentation de l'inférence causale aux EGAP Learning Days à Salima, Malawi, février 2017](https://egap.github.io/learningdays-resources/Slides/Examples/causality-malawi.pdf)

 - [La présentation de l'inférence causale aux EGAP Learning Days à l'Université Diego Portales à Santiago, Chili, mai 2016](https://egap.github.io/learningdays-resources/Slides/Examples/causality-santiago.pdf)

## Ressources

### Guide des méthodes EGAP

- Guide des méthodes EGAP [10 choses à savoir sur l'inférence causale](https://egap.org/resource/10-things-to-know-about-causal-inference/)

- Guide des méthodes EGAP [10 stratégies pour déterminer si X a causé Y](https://egap.org/resource/10-strategies-figuring-out-if-x-caused-y/)

- Guide des méthodes EGAP [10 choses à savoir sur les mécanismes](https://egap.org/resource/10-things-mechanisms/)

- Guide des méthodes EGAP [10 choses à savoir sur la validité externe](https://egap.org/resource/10-things-to-know-about-external-validity/)

### Livres, chapitres et articles {#causalinference-cites}

#### Classiques {#causalinference-classics}

- [@fisher_design_1935]. Fisher introduit l'idée de la randomisation et des tests d'hypothèses pour apprendre l'inférence causale.

- [@rubin:1974]. Rubin introduit l'idée de résultats potentiels et relie les conceptualisations contrefactuelles de la causalité à l'inférence statistique.

#### Revue actuelle

- [@brady2008causation].

- [@gerber_field_2012, Chapitre 1]. Ce livre est une excellente ressource pour de nombreux sujets du design expérimental.

- [@morgan_counterfactuals_2007, Chapitre 1]. Ce livre comprend de bons examples de raisonnement pour faire des assertions de causalité à partir de données d'observation.

- [@glennerster_running_2013]. Ceci est une excellente introduction pour mener des expériences de terrain illustrée par nombreux exemples.

### Notes d'orientation des politiques publiques EGAP

Quelques exemples de questions causales :

- [Note d'orientation des politiques publiques EGAP 38: Les campagnes d'éducation des électeurs à la radio sont-elles efficaces pour décourager les électeurs de voter pour des partis ou candidats qui s'engagent dans l'achat de voix ?](https://egap.org/resource/brief-38-diminishing-the-effectiveness-of-vote-buying-through-voter-education/)

- [Note d'orientation des politiques publiques EGAP 51: Les technologies de l'information et de communication gratuites et anonymes peuvent-elles renforcer la responsabilité locale et améliorer les prestations de services publics ?](https://egap.org/resource/does-information-technology-improve-public-service-delivery-lessons-from-uganda/)

- [Note d'orientation des politiques publiques EGAP 58: La responsabilisation bottom-up peut-elle améliorer les perspectives en matière de santé ?](https://egap.org/resource/does-bottom-up-accountability-work-evidence-from-uganda/)

- [Note d'orientation des politiques publiques EGAP 69: Une surveillance citoyenne bottom-up améliore-t-elle les prestations de services publics ?](https://egap.org/resource/brief-69-bottom-up-accountability-and-public-service-provision-in-brazil/)


