# Estimations et estimateurs {.tabset}

Les expériences aléatoires les expériences génèrent de bonnes suppositions sur le résultat moyen sous traitement et le résultat moyen sous contrôle.  Cela nous permet d'avoir des estimateurs sans biais des effets moyens du traitement.  Nous pouvons également utiliser la randomisation pour décrire comment les estimations générées par un estimateur peuvent varier d'une expérience à l'autre avec des erreurs standards et des intervalles de confiance.

Dans ce module, nous introduisons plusieurs types d'estimations.  Le choix de l'estimation est une décision scientifique et politique -- sur quelle quantité aimerions-nous en savoir plus ?  De plus, nous voulons sélectionner un estimateur approprié pour cette estimation dans le cadre du design de recherche.  Nous discutons de la façon dont les estimateurs sont appliqués aux données pour générer une estimation et comment caractériser sa variabilité.   


## Contenu

- Un **effet causal**, $\tau_i$, est une comparaison des résultats potentiels non observés pour chaque unité $i$.  Par exemple, cela peut être une différence ou un ratio de résultats potentiels non observés.  

- Pour en savoir plus sur $\tau_{i}$, on peut traiter $\tau_{i}$ comme **estimande** ou quantité cible à estimer (ce module) 
ou comme quantité cible sur laquelle émettre une hypothèse ([module de test d'hypothèse](hypothesis-testing.html)).

- Beaucoup de gens se concentrent sur **l'effet moyen du traitement (ATE)**, $\bar{\tau}=\sum_{i=1}^n
   \tau_{i}$, en partie parce qu'il permet **d'estimer** facilement.

- Un **estimateur** est une recette pour calculer une supposition 
sur la valeur d'un estimande. Par exemple, la différence entre la moyenne des résultats observés pour $m$ unités traitées et la moyenne des résultats observés pour $N-m$ unités non traitées est un estimateur de $\bar{\tau}$. 

- Différentes randomisations produiront différentes valeurs du même estimateur ciblant le même estimande. Une **erreur standard** résume cette variabilité dans un estimateur.

- Un **intervalle de confiance** de $100(1-\alpha)$% est un ensemble d'hypothèses qui ne peuvent être rejetées au niveau $\alpha$. Nous avons tendance à rapporter des intervalles de confiance contenant des hypothèses sur les valeurs de notre estimande et à utiliser notre estimateur comme statistique de test.

- Les estimateurs devraient (1) éviter les erreurs systématiques dans leur estimation de l'estimande (être sans biais); (2) varient peu dans leurs suppositions d'une expérience à l'autre (être précis ou efficace); et peut-être idéalement (3) converger vers l'estimande quand ils utilisent de plus en plus d'informations (être cohérent).

 - **Analyser en randomisant** dans le contexte de l'estimation signifie que (1) nos erreurs standards devraient mesurer la variabilité de la randomisation et (2) nos estimateurs devraient cibler des estimandes définis en termes de résultats potentiels.

 - Nous **ne contrôlons pas** les covariables lorsque nous analysons les données d'expériences aléatoires. Pourtant les covariables peuvent rendre notre estimation plus **précise**. C'est ce qu'on appelle **l'ajustement de covariance**. L'ajustement de covariance dans les expériences aléatoires diffère du contrôle des variables dans les études d'observation.

 - Une intervention politique (comme une lettre qui encourage l'exercice) peut *avoir l'intention* de changer un comportement par **une dose active** (exercice réel). Nous pouvons apprendre l'effet causal de l'intention en envoyent les lettres de façon aléatoire. C'est ce qu'on appele **l'effet d'intention de traiter** (intent to treat effect, **ITT**).
 
 - Nous pouvons apprendre sur l'effet causal de l'exercice réel en utilisant l'attribution aléatoire de lettres comme **instrument** la dose active (l'exercice lui-même) afin d'apprendre davantage sur l'effet causal de l'exercice **chez ceux qui changeraient leur comportement après avoir reçu la lettre**. Les versions d'effet causal moyen de ces effets sont souvent connues sous le nom de ** TODO complier average causal effect** ou **l'effet de traitement moyen local**.



## Slides

Vous trouverez ci-dessous des slides avec le contenu de base pour cette section.

- [Code source en R Markdown](https://egap.github.io/learningdays-resources/Slides/estimation-slides.Rmd)

- [Version PDF](https://egap.github.io/learningdays-resources/Slides/estimation-slides.pdf)

- [Version HTML](https://egap.github.io/learningdays-resources/Slides/estimation-slides.html)

Vous pouvez aussi lire les slides des précédents EGAP Learning Days:

 - [La présentation de l'estimation aux EGAP Learning Days à l'African School of Economics, Abomey-Calavi, juin 2019](https://egap.github.io/learningdays-resources/Slides/Examples/estimation-benin.pdf)

 - [La présentation de l'estimation aux EGAP Learning Days à l'Université des Andes, Bogotá, avril 2019](https://egap.github.io/learningdays-resources/Slides/Examples/estimation-bogota.pdf)

 - [La présentation de l'estimation aux EGAP Learning Days à l'Université catholique d'Uruguay, Montevideo, mars 2018](https://egap.github.io/learningdays-resources/Slides/Examples/estimation-montevideo.pdf)

 - [La présentation de l'estimation aux EGAP Learning Days à l'Université Diego Portales à Santiago, Chili, mai 2016](https://egap.github.io/learningdays-resources/Slides/Examples/estimation-santiago.pdf)

Vous pouvez également voir les problèmes d'estimation de l'effet de la dose active d'un traitement dans ces slides (ainsi que les problèmes causés par les données manquantes sur les résultats pour l'estimation de l’effet causal moyen) :

- [La présentation des problèmes de design aux EGAP Learning Days à l'African School of Economics, Abomey-Calavi, juin 2019 (first section reviews randomization designs)](https://egap.github.io/learningdays-resources/Slides/Examples/threats-benin.pdf)

- [La présentation des effets de débordement et de l'attrition aux EGAP Learning Days à Guatemala City, Guatemala, août 2017](https://egap.github.io/learningdays-resources/Slides/Examples/spillovers_attrition-guatemala.pdf)

- [La présentation des menaces aux EGAP Learning Days à Guatemala City, Guatemala, août 2017](https://egap.github.io/learningdays-resources/Slides/Examples/threats-guatemala.pdf)

- [La présentation des complications aux EGAP Learning Days à Salima, Malawi, février 2017](https://egap.github.io/learningdays-resources/Slides/Examples/complications-malawi.pdf)

- [La présentation des menaces aux EGAP Learning Days à l'Université Diego Portales à Santiago, Chili, mai 2016 (la section du milieu examine l'ITT et la non-conformité)](https://egap.github.io/learningdays-resources/Slides/Examples/threats-santiago.pdf)


## Ressources

### Guide des méthodes EGAP

 - Guide des méthodes EGAP [Les 10 effets de traitement que vous devez connaître](https://egap.org/resource/10-types-of-treatment-effect-you-should-know-about/)

 - Guide des méthodes EGAP [10 choses à savoir sur l'ajustement de covariante](https://egap.org/resource/10-things-to-know-about-covariate-adjustment/)

 - Guide des méthodes EGAP [10 choses à savoir sur les données manquantes](https://egap.org/resource/10-things-to-know-about-missing-data/)

 - Guide des méthodes EGAP [10 choses à savoir sur l'effet de traitement moyen local](https://egap.org/resource/10-things-to-know-about-the-local-average-treatment-effect/)

 - Guide des méthodes EGAP [10 choses à savoir sur les effets de TODO débordement](https://egap.org/resource/10-things-to-know-about-spillovers/)

### Livres, chapitres et articles

 - [@gerber_field_2012]. TODO Chapter 2.7 on excludability and non-interference, Chapter 3, Chapter 5 on one-sided noncompliance, Chapter 6 on two-sided noncompliance, Chapter 7 on attrition, Chapter 8 on interference between experimental units.

 - [@bowers2020causality].


### Outils

- [DeclareDesign](https://declaredesign.org)

- [Le package estimatr en R](https://declaredesign.org/r/estimatr/)

