# Considérations éthiques {.tabset}

*Une expérience aléatoire implique qu'un groupe d'humains change la vie d'un autre groupe d'humains.* Ceux qui travaillent pour le gouvernement le font naturellement --- leur travail même est de fournir à leur peuple de la nourriture, un abri, la sécurité, la justice etc. Les universitaires, dont les travaux n'ont généralement pas d'impacts immédiats sur le public, doivent également se rappeler d'examiner attentivement comment leurs recherches pourraient changer la vie des personnes exposées à l'intervention, ainsi que de celles qui ne l'ont pas été. Lorsqu'une personne influence la vie d'une autre, l'influenceur a la responsabilité de ne pas nuire à la personne influencée.

Ce module traite des sujets de base sur l'éthique de la recherche, tels que la vie privée et l'autonomie ; les principes de base comme le respect des personnes, la bienveillance et la justice ; et comment le consentement éclairé aide à communiquer ces principes aux participants de l'étude.

## Contenu

 - La recherche doit peser les **bénéfices potentiels** des connaissances à tirer de la recherche par rapport aux **dommages potentiels** qu'elle peut causer aux sujets humains.

 - Que ressentiriez-vous si vous étiez un sujet de recherche dans votre étude ? Dans le groupe contrôle ? Dans le groupe de traitement ? Un membre de statut relativement élevé dans la communauté ? Un membre de statut relativement bas dans la communauté ?

 - Principes clés : **la confidentialité** et **l'autonomie**.

 - Principes de base du rapport Belmont : **respect des personnes, bienveillance, justice**.

 - **Consentement éclairé** : Pouvez-vous garantir que les sujets de recherche ont la liberté de refuser de participer et/ou d'abandonner l'étude s'ils le souhaitent ? Pouvez-vous vous assurer que les sujets de recherche peuvent signaler les problèmes qui pourraient survenir ?

 - Défis de la recherche expérimentale en sciences sociales en général :

    - Beaucoup plus de personnes peuvent profiter (ou souffrir) de votre intervention que ceux participant directement à votre étude

    - Modifier les résultats des élections ou changer la corruption peuvent entraîner de grands changements sociétaux. Est-ce aller au-delà du domaine de la recherche ?

## Slides

Vous trouverez ci-dessous des slides avec le contenu de base pour cette section.

 - [Code source en R Markdown](https://egap.github.io/learningdays-resources/Slides/ethics-slides.Rmd)

 - [Version PDF](https://egap.github.io/learningdays-resources/Slides/ethics-slides.pdf)

 - [Version HTML](https://egap.github.io/learningdays-resources/Slides/ethics-slides.html)

## Ressources

- [Principes de recherche et travaux sur l'éthique de EGAP](https://egap.org/ethics/)

- [Principes et lignes directrices pour la recherche sur des sujets humains de APSA](https://connect.apsanet.org/hsr/principles-and-guidance/)

- [Le rapport Belmont](https://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/index.html)

- [Les comités de revue éthique institutionnels aux USA](https://www.youtube.com/watch?v=U8fme1boEbE)

- [Exemple : Éthique de la recherche à l'Université d'Oxford au Royaume-Uni](https://researchsupport.admin.ox.ac.uk/governance/ethics)

- [Exemple : Éthique pour les chercheurs dans l'UE](https://ec.europa.eu/research/participants/data/ref/fp7/89888/ethics-for-researchers_en.pdf)

- [Exemple : Éthique de la recherche à l'Université catholique du Chile](http://eticayseguridad.uc.cl/)

### Livres, chapitres et articles

- [@Asieduetal2021ethics]

- [@Evans2021ethics] <!--[pdf](https://www.cgdev.org/sites/default/files/WP565-Evans-Ethical-issues-and-RCTs.pdf) -->

### Articles et plans de pré-analyse

Exemples de plans de pré-analyse et d'articles sur les considérations éthiques :

- [Plan de pré-analyse : les effets des bons non-alimentaires dans un contexte humanitaire, le cas du programme de réponse rapide aux mouvements de population au Congo](https://osf.io/eutx7/)

- [Article : Appendix E.1 Lutter contre la violence à l'égard des femmes en encourageant la dénonciation : une expérience dans les médias de masse en Ouganda rural](http://jasper-cooper.com/papers/Green_et_al.pdf)
