# Tests d'hypothèses {.tabset}

Ce n'est pas possible d'observer directement les effets causaux à cause du *problème fondamental de l'inférence causale* ([module de l'inférence causale](causal-inference.html)).
Comment pouvons-nous en savoir plus sur ces *effets causaux non observés* en utilisant ce que nous observons ?
Dans une expérience aléatoire, nous pouvons évaluer des *suppositions* ou des *hypothèses* sur les effets causaux non observés.
Pour ce faire, nous comparons ce que nous observons dans une expérience à ce que nous observerions si nous pouvions répéter la manipulation expérimentale et que la supposition ou l'hypothèse était vraie.

Dans ce module, nous présentons les tests d'hypothèses, leur lien avec l'inférence causale, les $p$-valeurs et ce qu'il faut faire lorsque nous avons plusieurs hypothèses à tester.

## Contenu

- Qu'est-ce qu'une **bonne hypothèse** ?

- La relation entre les tests d'hypothèses et l'inférence causale.

- **Tests d'hypothèses**.

     - L'hypothèse nulle.

     - Estimateurs vs. statistiques de test.

     - Dans une expérience, une distribution de référence pour un test d'hypothèse provient du design expérimental et de la randomisation.

     - Les $p$-valeurs et comment interpréter les résultats des tests d'hypothèses.

- Un bon test d'hypothèse doit (1) rarement mettre en doute la vérité (c'est-à-dire avoir un taux de faux positifs contrôlé et faible) et (2) distinguer facilement le signal du bruit (c'est-à-dire mettre souvent en doute les contrevérités ; avoir une puissance statistique élevée) .

- Comment saurons-nous si notre test d'hypothèse performe bien ? ([Analyse de puissance statistique](statistical-power-and-design-diagnosands.html) a son propre module).

    - Taux de faux positifs.
    
    - Couverture correcte de l'intervalle de confiance.

    - Évaluer le taux de faux positifs d'un test d'hypothèse pour un design et un choix de statistique de test donnés;
      cas d'un essai aléatoire par grappe (cluster) et l'erreur standard robuste pour cluster.

- Soyez prudent lorsque vous testez **de nombreuses hypothèses**, par exemple quand vous avez plus de deux bras de traitement ou que vous évaluez les effets d'un traitement sur plusieurs résultats. Nous devons veiller à **ajuster les $p$-valeurs ou les intervalles de confiance** pour refléter le nombre de tests ou d'intervalles produits.

## Slides

Vous trouverez ci-dessous des slides avec le contenu de base de notre conférence sur les tests d'hypothèses. Vous pouvez les utiliser directement ou les copier localement avant de les éditer.

 - [Code source en R Markdown](https://egap.github.io/learningdays-resources/Slides/hypothesistesting-slides.Rmd)

 - [Version PDF](https://egap.github.io/learningdays-resources/Slides/hypothesistesting-slides.pdf)

 - [Version HTML](https://egap.github.io/learningdays-resources/Slides/hypothesistesting-slides.html)

Vous pouvez aussi lire les slides des précédents EGAP Learning Days :

 - [Présentation des tests d'hypothèses aux EGAP Learning Days à l'African School of Economics, Abomey-Calavi, juin 2019](https://egap.github.io/learningdays-resources/Slides/Examples/hypothesistesting-benin.pdf)

 - [Présentation des tests d'hypothèses aux EGAP Learning Days à l'Université des Andes, Bogotá, avril 2019](https://egap.github.io/learningdays-resources/Slides/Examples/hypothesistesting-bogota.pdf)

 - [Présentation des tests d'hypothèses aux EGAP Learning Days à l'Université catholique d'Uruguay, Montevideo, mars 2018](https://egap.github.io/learningdays-resources/Slides/Examples/hypothesistesting-montevideo.pdf)

 - [Présentation des tests d'hypothèses aux EGAP Learning Days à Guatemala City, Guatemala, août 2017](https://egap.github.io/learningdays-resources/Slides/Examples/hypothesistesting-guatemala.pdf)

 - [Présentation des tests d'hypothèses aux EGAP Learning Days à Salima, Malawi, février 2017](https://egap.github.io/learningdays-resources/Slides/Examples/hypothesistesting-malawi.pdf)

 - [Présentation des tests d'hypothèses aux EGAP Learning Days à l'Université Diego Portales à Santiago, Chili, mai 2016](https://egap.github.io/learningdays-resources/Slides/Examples/hypothesistesting-santiago.pdf)


## Ressources

### Guide des méthodes EGAP

  - Guide des méthodes EGAP [10 choses à savoir sur les tests d'hypothèses](https://egap.org/resource/10-things-to-know-about-hypothesis-testing/)

  - Guide des méthodes EGAP [10 choses à savoir sur les comparaisons multiples](https://egap.org/resource/10-things-to-know-about-multiple-comparisons/)

### Livres, chapitres et articles

 - [@gerber_field_2012]. Chapitre 3 : Distributions d'échantillonnage, inférence statistique et tests d'hypothèses.
 
 - [@rosenbaum2010design]. Chapitre 2 : Inférence causale dans les expériences aléatoires.
 
 - [@rosenbaum2017observation]. Partie I : Expériences aléatoires.

