# Mesure {.tabset}

Pour estimer des effets et tester des hypothèses, nous utilisons souvent un résultat mesuré à l'aide de données quantitatives provenant d'enquêtes, de jeux comportementaux ou d'archives administratives. Pour les questions causales, nous utilisons généralement des données de résultats immédiats et finaux et de mécanismes de base. Nous utilisons des données de base pour identifier les sous-groupes pertinents, ajuster nos estimations ou randomiser notre traitement par bloc. Les mesures doivent être valides et fiables. Sachez que les données peuvent être bruitées (erreur aléatoire) et/ou biaisées (erreur systématique).

Ce module traite *que mesurer* et *comment mesurer*. Il montre à quel point une bonne mesure est liée à la [conception de recherche](https://egap.github.io/learningdays-resources/Exercises/design-form.Rmd) et à la [puissance statistique](statistical-power-and-design-diagnosands.html).

## Contenu

 - Lorsque nous représentons un attribut d'une unité par un nombre, une lettre, un mot ou un symbole d'une manière systématique (par exemple, dans une case d'un simple dataset), nous **mesurons**.

 - Une mesure **valide** d'un concept ou d'un phénomène d'intérêt doit clairement représenter cette entité sous-jacente et souvent abstraite.

 - Une mesure **fiable** d'un concept donnerait la même valeur pour l'unité de mesure (par exemple, une personne ou un village) si les conditions ne changent pas.

 - Nous pouvons évaluer nos théories de mesure en utilisant plusieurs approches pour mesurer les résultats, les covariables ou les différences entre unités en fonction des différents rendus des mécanismes causaux.

 - Pour votre [conception de recherche](https://egap.github.io/learningdays-resources/Exercises/design-form.Rmd), une mesure invalide peut rendre difficile la distinction efficace des explications alternatives de la relation entre le traitement et les résultats.

 - Une mesure non fiable peut diminuer [la puissance statistique](statistical-power-and-design-diagnosands.html).
 
 - Une mesure difficile peut nécessiter une étude pilote centrée sur la mesure elle-même.

## Slides

Vous trouverez ci-dessous des slides avec le contenu de base de notre conférence sur la mesure. Vous pouvez les utiliser directement ou les copier localement avant de les éditer.

 - [Code source en R Markdown](https://egap.github.io/learningdays-resources/Slides/measurement-slides.Rmd)

 - [Version PDF](https://egap.github.io/learningdays-resources/Slides/measurement-slides.pdf)

 - [Version HTML](https://egap.github.io/learningdays-resources/Slides/measurement-slides.html)

## Ressources

### Guide des méthodes EGAP

- Guide des méthodes EGAP [10 choses à savoir sur la mesure dans les expériences](https://egap.org/resource/10-things-to-know-about-measurement-in-experiments/)

- Guide des méthodes EGAP [10 choses à savoir sur la conception de sondage](https://egap.org/resource/10-things-to-know-about-survey-design/)

- Guide des méthodes EGAP [10 choses à savoir sur l'implémentation de sondage](https://egap.org/resource/10-things-to-know-about-survey-implementation/)

### Livres, chapitres et articles

 - [@adcocoll:2001]

 - [@scacco_can_2018]
 
 - [@shadish2002experimental]

 - [@vicente_is_2014]

### Notes d'orientation des politiques publiques EGAP

*Grâce à des données d'enquête à plusieurs échelles*

 - [Note d'orientation des politiques publiques EGAP 58 : La responsabilisation bottom-up fonctionne-t-elle ?](https://egap.org/resource/does-bottom-up-accountability-work-evidence-from-uganda/)

*Grâce aux sms*

 - [Note d'orientation des politiques publiques EGAP 27 : Technologies de l'information et de la communication et politiciens en Uganda](https://egap.org/resource/brief-27-ict-and-politicians-in-uganda/)

 - [Note d'orientation des politiques publiques EGAP 56 : Signaler la corruption au Nigéria](https://egap.org/resource/reporting-corruption-in-nigeria-testing-the-effects-of-norms-nudges/)

*Grâce aux données administratives*

 - [Note d'orientation des politiques publiques EGAP 16 : Effets de débordement des observateurs électoraux au Ghana](https://egap.org/resource/brief-16-spillover-effects-of-observers-in-ghana/)

 - [Note d'orientation des politiques publiques EGAP 67 : Administration électorale au Kenya](https://egap.org/resource/electoral-administration-in-kenya/)
