# Other Topics {.tabset}

Ici, nous fournissons des liens vers des ressources pour aider les gens à en apprendre davantage sur des sujets qui ne peuvent pas être traités en profondeur pendant le workshop mais qui sont importants pour le design expérimental.

## Contenu
 
- Workflow
  - Les gens ont une mémoire limitée, nous avons besoin de règles et d'outils pour nous aider à nous souvenir et à partager
  - La reproductibilité repose sur du code clair, efficace et archivé

- Validition externe
  - Une grande partie de ce livre traite de la validité interne.
  - Cela ne vous aide pas à extrapoler immédiatement à d'autres populations.
  - Quels sont les compromis ? Comment extrapoler ?

- Inférence aléatoire et procédures en ri2
  - L'inférence aléatoire est une méthode pour le calcul des p-valeurs pour les tests d'hypothèse
  - ir2 est un package R qui vous permet d'exécuter des simulations pour le calcul des p-valeurs de l'inférence aléatoire pour les différentes estimandes

- Lecture des résultats
  - Comment comprendre et interpréter la sortie de régression?
  
- Intégration une recherche qualitative

- Designs évolutifs
  - La plupart des designs sont statiques : c'est-à-dire que les mêmes procédures d'assignation des traitements et de mesure des résultats sont appliquées tout au long de l'expérience.
  - Les designs évolutifs ajustent l'assignation du traitement et du contrôle sur la base d'une analyse intermédiaire du résultat de l'expérience.

- Meta-analyse

## Slides

## Ressources

### Guide des méthodes EGAP

- [10 choses à savoir sur la gestion de project](https://egap.org/resource/10-things-to-know-about-project-workflow/)
- [10 choses à savoir sur l'inférence aléatoire](https://egap.org/resource/10-things-to-know-about-randomization-inference/)
- [10 choses à savoir sur les données manquantes](https://egap.org/resource/10-things-to-know-about-missing-data/)

### Livres, chapitres et articles

 - [Comment améliorer votre relation avec votre futur moi] (https://github.com/jwbowers/workflow)
 - [Berkeley Initiative pour la transparence en sciences sociales] (https://www.bitss.org/)
