# Mise en pratique {.tabset}

Une fois que vous avez rempli le [formulaire de conception de recherche](research-design.html) et reçu un financement, ou peut-être même terminé votre projet, vous serez confronté à une série d'autres défis.

Ce module répertorie quelques-uns de ces défis et y associe des liens et des références utiles, notamment à propos de workflow, de plans de pré-analyse.

## Contenu

### Workflow

Comment vous souviendrez-vous de ce que vous avez fait un an, deux ou dix ans ? Comment vous assurerez-vous que les tableaux, graphiques et résultats que vous utilisez pour guider les décisions stratégiques ne sont pas le résultat d'une erreur de copier-coller  ? Ou que votre code n'impliquait pas une variable erronée par inadvertance, aboutissant à la conclusion opposée à celle que vous venez de livrer au ministre de la Santé  ? Bien qu'aucune approche ne puisse empêcher toutes les erreurs, certaines approches de base pour organiser le travail peuvent vous aider. Ces approches permettent de transformer d'un essai rapide pour la fin d'un trimestre (jamais revu sérieusement par la suite) à un travail de collaboration de plusieurs décennies (ou siècles) avec d'autres universitaires et décideurs politiques à travers le temps et l'espace.

  - [Sur l'utilisation de 'Dark Logic' pour anticiper l'échec et le planifier](https://jech.bmj.com/content/jech/69/1/95.full.pdf).

  - [L'approche pre-mortem au management de projet](https://en.wikipedia.org/wiki/Pre-mortem) pour laquelle l'équipe imagine qu'un projet a échoué avant de lancer.

### Faire face aux contraintes du monde réel

 - Travailler avec des partenaires : humilité et respect et écoute
 - Budgets et limites physiques sur la taille de l'échantillon expérimental (limites sur le contrôle de la randomisation)
    - Exemple : des conceptions de randomisation par grappe avec un petit nombre de grappes

### Plans de pré-analyse

### Comment présenter un tableau ou un graphique des résultats

 - Tufte on Ink to Information Ratio.
 - @gerber_field_2012, Chapter 13

### Validité externe, généralisation, mise à l'échelle

## Ressources

### Guide des méthodes EGAP

  - Guide des méthodes EGAP [10 choses à savoir sur la gestion de project](https://egap.org/resource/10-things-to-know-about-project-workflow/) (which builds on @bowers2016future).
  - Guide des méthodes EGAP [10 choses à savoir sur les plans de pré-analyse](https://egap.org/resource/10-things-to-know-about-pre-analysis-plans/)

### Livres, chapitres et articles

  - @cartwright2012evidence met en garde contre l'utilisation simpliste des résultats d'ECR pour orienter les politiques publiques.

  - See also @bowerstesta2019epp et surtout leur discussion sur @giacomini2009theory en ce qui concerne l'importance de la théorie pour relier la conception de recherche et les politiques publiques.

### Notes d'orientation des politiques publiques EGAP

