# Randomisation {.tabset}

Le module sur [l'inférence causale](inférence-causale.html) aborde le rôle important de la randomisation pour tirer des inférences valides à partir d'une comparaison des groupes traités et non traités. Dans ce module, nous passons de la théorie aux cas concrets pour votre conception de recherche.

Nous introduisons quatre façons courantes de randomiser le traitement -- simple, complète, par bloc, et en grappe (cluster) -- et nous expliquons quand ces différents types de randomisation sont disponibles et appropriés.  Nous couvrons également plusieurs conceptions courantes, y compris les conceptions factorielles et les conceptions incitatives.  Le module fournit des conseils sur l'implémentation, y compris les bonnes pratiques pour vérifier l'homogénéité et assurer la reproductibilité.

## Contenu

- Qu'est-ce que la **randomisation** ? L'assignation aléatoire **n'est pas** la même chose que l'échantillonnage aléatoire.

- Quatre façons courantes de randomiser le traitement :

    - **Simple** : assigner de manière aléatoire les unités au traitement (comme un tirage au sort).

    - **Complète** : au sein d'une liste d'unités éligibles, assigner un nombre fixe d'unités au traitement (comme un tirage d'une urne sans remise).

    - **Par bloc (ou stratifiée)** : assigner un traitement dans des strates ou des blocs spécifiques, comme si vous meniez une expérience dans chaque bloc.
      
    - **Par grappe (cluster)** : assigner des groupes d'observation (grappes ou clusters) à la même condition de traitement.
    
    
- Quelques conceptions courantes :
    
    - **Accès randomisé** : randomiser la disponibilité du traitement.
    
    - **Accès randomisé differé** : randomiser le timing de l'accès au traitement.
    
    - **Factorielle** : randomiser les unités en combinant les bras de traitement.
    
    - **Incitative** : randomiser l'incitation à prendre le traitement.

- Comment vérifier si votre randomisation a produit des groupes homogènes sur les caractéristiques observables ? En règle générale, nous effectuons des tests de randomisation, également appelés tests d'homogénéité. On peut, par exemple, utiliser le test omnibus $d^2$ de `xBalance` dans le package `RItools` (car c'est une inférence de randomisation) ou on peut approximer ce résultat avec un test $F$.

- La randomisation a **des limites**.  Nous en discutons ici et nous vous orientons vers le module sur [les menaces](menaces-affectant-la-validité-interne-des-expériences-aléatoires.html) pour en savoir plus.

## Slides

Vous trouverez ci-dessous des slides avec le contenu de base de notre conférence sur la randomisation. Vous pouvez les utiliser directement ou les copier localement avant de les éditer.

- [Code source en R Markdown](https://egap.github.io/learningdays-resources/Slides/randomization-slides.Rmd)

- [Version PDF](https://egap.github.io/learningdays-resources/Slides/randomization-slides.pdf)

- [Version HTML](https://egap.github.io/learningdays-resources/Slides/randomization-slides.html)

Les fichiers liés montrent comment [faire une randomisation reproducible en R](https://egap.github.io/learningdays-resources/Exercises/randomization-exercises.Rmd).
Vous pouvez également voir plus d'exemples de randomisation en R ici : [10 choses à savoir sur la randomisation](https://egap.org/resource/10-things-to-know-about-randomization/).

Vous pouvez aussi lire les slides des précédentes journées d'apprentissage du réseau EGAP :

- [Présentation des problèmes de conception aux journées d'apprentissage du réseau EGAP à l'African School of Economics, Abomey-Calavi, juin 2019 (la première section passe en revue les conceptions de randomisation)](https://egap.github.io/learningdays-resources/Slides/Examples/threats-benin.pdf)

- [Présentation de la randomisation aux journées d'apprentissage du réseau EGAP à l'Université des Andes, Bogotá, avril 2019](https://egap.github.io/learningdays-resources/Slides/Examples/randomization-bogota.pdf)

- [Présentation de la randomisation aux journées d'apprentissage du réseau EGAP à l'Université catholique d'Uruguay, Montevideo, mars 2018](https://egap.github.io/learningdays-resources/Slides/Examples/randomization-montevideo.pdf)

- [Présentation de la randomisation aux journées d'apprentissage du réseau EGAP à Guatemala City, Guatemala, août 2017](https://egap.github.io/learningdays-resources/Slides/Examples/randomization-guatemala.pdf)

- [Présentation de la randomisation aux journées d'apprentissage du réseau EGAP à Salima, Malawi, février 2017](https://egap.github.io/learningdays-resources/Slides/Examples/randomization-malawi.pdf)

- [Présentation de la randomisation aux journées d'apprentissage du réseau EGAP à l'Université Diego Portales à Santiago, Chili, mai 2016](https://egap.github.io/learningdays-resources/Slides/Examples/randomization-santiago.pdf)


## Ressources

### Guide des méthodes EGAP

- Guide des méthodes EGAP [10 choses à savoir sur la randomisation](https://egap.org/resource/10-things-to-know-about-randomization/)

- Guide des méthodes EGAP [10 choses à savoir sur la randomisation par grappe (cluster)](https://egap.org/resource/10-things-to-know-about-cluster-randomization/)

### Livres, chapitres et articles

- [Procédures opérationnelles standard pour le laboratoire de Don Green à l'Université de Columbia](https://github.com/acoppock/Green-Lab-SOP). Un ensemble complet de procédures et de règles empiriques pour mener des études expérimentales.

- [@glennerster_running_2013]. Chapitre 2 sur la randomisation.

- [@gerber_field_2012]. Chapitre 2 : Inférence causale et expérimentation

### Notes d'orientation des politiques publiques EGAP

*Conceptions factorielles*

- [Note d'orientation des politiques publiques EGAP 57 : Comment les médias influencent les normes sociales : la preuve au Mexique](https://egap.org/resource/how-media-influence-social-norms-evidence-from-mexico/)

- [Note d'orientation des politiques publiques EGAP 58 : La responsabilisation bottom-up fonctionne-t-elle  ?](https://egap.org/resource/does-bottom-up-accountability-work-evidence-from-uganda/)

*Randomiser l'accès*

- [Note d'orientation des politiques publiques EGAP 24 : Réduire l'accaparation par les élites dans les îles Salomon](https://egap.org/resource/brief-24-reducing-elite-capture-in-the-solomon-islands/)

*Accès randomisé differé*

  - [Note d'orientation des politiques publiques EGAP 35 : Réduire la récidive parmi les détenus libérés](https://egap.org/resource/brief-35-reducing-reconvictions-among-released-prisoners/)

  - [Note d'orientation des politiques publiques EGAP 60 : Réduire le soutien des jeunes à la violence grâce à la formation et aux transferts de cash en Afghanistan](https://egap.org/resource/reducing-youth-support-for-violence-through-training-and-cash-transfers-in-afghanistan/)

*Randomisation par grappe (cluster)*

  - [Note d'orientation des politiques publiques EGAP 22 : Pousser au vote](https://egap.org/resource/brief-22-getting-out-the-vote/)

*Randomisation combinée par grappe et par bloc*

  - [Note d'orientation des politiques publiques EGAP 54 : Révélations de malversations des politicens en place](https://egap.org/resource/evidence-from-mexico-the-effect-of-incumbent-malfeasance-revelations/)

  - [Note d'orientation des politiques publiques EGAP 56 : Signaler la corruption](https://egap.org/resource/reporting-corruption-in-nigeria-testing-the-effects-of-norms-nudges/)


### Outils

- [RItools](https://cran.r-project.org/web/packages/RItools/index.html), un ensemble d'outils pour l'inférence de randomisation, y compris le test d'homogénéité.


### Courtes vidéos explicatives

 - [Randomisation vs. échantillonnage aléatoire](https://www.youtu.be/02A61b3hxvA)
 
 - [Randomisation par grappe vs. par bloc](https://www.youtu.be/bL2U9z8hX1k)
 
