# Processus de design de recherche

Ce livre vise à vous aider à comprendre et à concevoir des expériences de terrain aléatoires.  Avant d'entrer dans le détail du design de recherche, nous avons besoin d'une bonne question de recherche - une question qui fera progresser les connaissances ou aidera à prendre une décision politique, ou les deux. Il n'y a pas de recette simple pour trouver ou développer une bonne question scientifique ou politique, mais nos théories sont importantes pour articuler les bonnes questions qui sous-tendent une recherche percutante. Après avoir formulé notre question, nous développons le meilleur design possible dans les limites de nos moyens, en utilisant notre connaissance de l'inférence causale et des statistiques présentée dans les modules qui suivent.

Ce module présente le [formulaire de design de recherche EGAP](https://egap.github.io/learningdays-resources/Exercises/design-form.Rmd), une checklist pour vous guider à travers les nombreuses étapes du processus de recherche. Les Learning Days sont organisés autour du formulaire de design de recherche. Nous vous incitons à utilser le logiciel [DeclareDesign](http://declaredesign.org) pour explorer les implications des différents choix que nous pourrions faire pour nos designs de recherche. Enfin, ce module aborde les plans de pré-analyse et de pré-enregistrement. Lorsque nous planifions nos analyses et rendons ces plans publics, nous améliorons nos chances de convaincre les autres avec nos résultats.

## Contenu

- Une **bonne question de recherche** fait progresser la science et/ou est une question dont la réponse éclairera une décision politique.

- Certains **designs de recherche** sont mieux pour répondre à certaines questions. Nous voulons choisir le design qui répond le mieux à nos questions clés compte tenu des contraintes et de nos moyens.

- Les questions que nous posons découlent --- souvent implicitement --- de nos valeurs et de notre compréhension du fonctionnement du monde. Ces **théories** rendent nos questions pertinentes. Et les expériences que nous réalisons nous renseignent sur la théorie. Cependant, nous espérons que les preuves et les données issues de ces designs de recherche amélioreront notre compréhension.

- Composants de base d'un design de recherche

- Présentation des composants de base de [formulaire de design de recherche EGAP](https://egap.github.io/learningdays-resources/Exercises/design-form.html).

- Introduction de package [DeclareDesign](http://declaredesign.org) pour le design de recherche.

- L'évolution des sciences sociales s'oriente vers **l'examen des designs, au lieu de l'examination des résultats**.

- **Le pré-enregistrement** -- ce que c'est, pourquoi et comment nous devons le faire.


## Slides

Vous trouverez ci-dessous des slides avec le contenu de base de notre conférence sur le design de recherche. Vous pouvez les utiliser directement ou les copier localement avant de les éditer.

- [Code source en R Markdown](https://egap.github.io/learningdays-resources/Slides/researchdesignform-slides.Rmd)

- [Version PDF](https://egap.github.io/learningdays-resources/Slides/researchdesignform-slides.pdf)

- [Version HTML](https://egap.github.io/learningdays-resources/Slides/researchdesignform-slides.html)

Vous pouvez aussi lire les slides des précédents EGAP Learning Days:

 - [Présentation de DeclareDesign aux EGAP Learning Days à l'Université catholique d'Uruguay, Montevideo, mars 2018](https://egap.github.io/learningdays-resources/Slides/Examples/declare_design-montevideo.pdf)

 - [Présentation de DeclareDesign aux EGAP Learning Days à Salima, Malawi, février 2017](https://egap.github.io/learningdays-resources/Slides/Examples/declare_design-malawi.pdf)

 - [Présentation de DeclareDesign  aux EGAP Learning Days à l'Université Diego Portales à Santiago, Chili, mai 2016](https://egap.github.io/learningdays-resources/Slides/Examples/declare_design-santiago.pdf)

Vous pouvez également voir les slides des Design Talks lors des précédents EGAP Learning Days, où les présentateurs se concentrent sur les problèmatiques relatives au design de la recherche, plutôt qu'aux résultats:

 - [Design Talk aux EGAP Learning Days à l'African School of Economics, Benin, mars 2018](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_2-benin.pdf)

 - [Design Talk 1 aux EGAP Learning Days à l'Université catholique d'Uruguay, Montevideo, mars 2018](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_1-montevideo.pdf)

 - [Design Talk 2 aux EGAP Learning Days à l'Université catholique d'Uruguay, Montevideo, mars 2018](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_2-montevideo.pdf)

 - [Design Talk 3 aux EGAP Learning Days à l'Université catholique d'Uruguay, Montevideo, mars 2018](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_3-montevideo.pdf)

 - [Design Talk 1 aux EGAP Learning Days à l'Université Diego Portales à Santiago, Chili, mai 2016](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_1-santiago.pdf)

 - [Design Talk 2 aux EGAP Learning Days à l'Université Diego Portales à Santiago, Chili, mai 2016](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_2-santiago.pdf)

 - [Design Talk 3 aux EGAP Learning Days à l'Université Diego Portales à Santiago, Chili, mai 2016](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_3-santiago.pdf)

 - [Design Talk aux EGAP Learning Days à Guatemala City, Guatemala, août 2017](https://egap.github.io/learningdays-resources/Slides/Examples/research_design-guatemala.pdf)

## Formulaire de design et pré-enregistrement

- [Formulaire de design de recherche EGAP](https://egap.github.io/learningdays-resources/Exercises/design-form.html). Une checklist que nous avons créée pour les Learning Days pour vous guider à travers les étapes du processus de recherche.
     - [Version Docx](https://egap.github.io/learningdays-resources/Exercises/design-form.docx)

     - [Version PDF](https://egap.github.io/learningdays-resources/Exercises/design-form.pdf)

     - [Version HTML](https://egap.github.io/learningdays-resources/Exercises/design-form.html)

- Liens vers les répertoires pour pré-enregistrement/plans de pré-analyse :

    - Le registre EGAP, hébergé par OSF (https://egap.org/registry/)

    - Le registre AEA RCT (https://www.socialscienceregistry.org/)

    - OSF (https://osf.io/registries)

- Exemples d'autres pré-enregistrements/plans de pré-analyse :

    - SMS au Mozambique du [gouvernement fédéral américain](https://oes.gsa.gov/projects/sms-mozambique/)

    - Caméras portatives pour les policiers du [Lab @ DC](https://osf.io/472zh)

## Ressources

### Guide des méthodes EGAP

- Guide des méthodes EGAP [10 choses à savoir sur les plans de pré-analyse](https://egap.org/resource/10-things-to-know-about-pre-analysis-plans/)

- Guide des méthodes EGAP [10 choses à savoir sur la mesure dans les expériences](https://egap.org/resource/10-things-to-know-about-measurement-in-experiments/)


### Livres, chapitres et articles

- [Pré-enregistrement comme outil pour renforcer l'évaluation fédérale](https://oes.gsa.gov/assets/files/preregistration-as-a-tool-in-federal-evaluation.pdf). Le livre blanc de l'Office of Evaluation Sciences du gouvernement américain. Vous pouvez également voir leurs exemples de plans de pré-analyse pour [toutes leurs pages d'expériences de terrain](https://oes.gsa.gov/work/).

- [@christensen_transparent_2019]. Le livre résume les nouvelles approches de la recherche en sciences sociales sur la transparence et la reproductibilité.

- [@gerber_field_2012].  Le chapitre 12 comprend quelques exemples de designs de recherche expérimentale.

### Outils

- [DeclareDesign](https://declaredesign.org/), un ensemble passionnant et complet d'outils logiciels pour décrire, évaluer et mener des recherches empiriques.

