---
output:
  pdf_document: default
  html_document: default
---
# Puissance statistique et diagnostics de conception {.tabset}

Avant de commencer une étude, nous aimerions savoir si notre conception a la puissance statistique nécessaire pour détecter un effet s'il existe.  Il est difficile d'apprendre d'une étude qui n'a pas une puissance statistique suffisante. Sans une puissance statistique suffisante, nous ne savons pas si un résultat nul signifie qu'il n'y a pas eu d'effet, ou que nous n'avons pas réussi à détecter un effet non nul qui existe. Une analyse de puissance statistique peut vous aider à améliorer votre conception et à mieux répartir vos ressources. Cela peut même vous aider à décider de ne pas mener l'étude.

Dans ce module, nous introduisons la puissance statistique, les approches de base pour calculer la puissance par calcul analytique ou par simulation, et comment les caractéristiques de conception telles que les blocs, l'ajustement des covariables et les grappes (clusters) ont un impact sur la puissance statistique.

## Contenu

 - **La puissance statistique** est la capacité d'une étude à détecter un effet s'il existe.
 
 - **L'analyse de puissance** s'effectue avant la réalisation d'une étude.  Cela aide à déterminer l'échantillon dont on a besoin ou les effets que l'on peut détecter. C'est une étape essentielle dans la conception de recherche et cela aide à communiquer sur sa conception.

 - Méthodes courantes de calcul de puissance :
 
      - Calculs de puissance **analytique** (en utilisant une formule)
 
      - **Simulations** (par exemple, en utilisant DeclareDesign)

 - **L'ajustement des covariables** et **des blocs** peut augmenter la puissance statistique.

 - Pour les **conceptions par grappe** il faut tenir compte de la corrélation intra-grappe (la variance intra-grappe par rapport à la variance globale).
 
 - La puissance statistique est étroitement liée à [la conception de l'étude](processus-de-conception-de-recherche.html), aux [tests d'hypothèses](tests-dhypothèses.html) et à [l'estimation](paramètres-et-estimateurs.html).

## Slides
Vous trouverez ci-dessous des slides avec le contenu de base de notre conférence sur la puissance statistique. Vous pouvez les utiliser directement ou les copier localement avant de les éditer.

 - [Code source en R Markdown](https://egap.github.io/learningdays-resources/Slides/power-slides.Rmd)

 - [Version PDF](https://egap.github.io/learningdays-resources/Slides/power-slides.pdf)

 - [Version HTML](https://egap.github.io/learningdays-resources/Slides/power-slides.html)

Vous pouvez aussi lire les slides des précédentes journées d'apprentissage du réseau EGAP :

 - [Présentation de la puissance statistique des journées d'apprentissage du réseau EGAP à l'African School of Economics, Abomey-Calavi, juin 2019](https://egap.github.io/learningdays-resources/Slides/Examples/power-benin.pdf)

 - [Présentation de la puissance statistique des journées d'apprentissage du réseau EGAP à l'Université des Andes, Bogotá, avril 2019](https://egap.github.io/learningdays-resources/Slides/Examples/power-bogota.pdf)

 - [Présentation de la puissance statistique des journées d'apprentissage du réseau EGAP à l'Université catholique d'Uruguay, Montevideo, mars 2018](https://egap.github.io/learningdays-resources/Slides/Examples/power-montevideo.pdf)

 - [Présentation de la puissance statistique des journées d'apprentissage du réseau EGAP à Guatemala City, Guatemala, août 2017](https://egap.github.io/learningdays-resources/Slides/Examples/power-guatemala.html)

 - [Présentation de la puissance statistique des journées d'apprentissage du réseau EGAP à Salima, Malawi, février 2017](https://egap.github.io/learningdays-resources/Slides/Examples/power-malawi.pdf)

 - [Présentation de la puissance statistique des journées d'apprentissage du réseau EGAP à l'Université Diego Portales à Santiago, Chili, mai 2016](https://egap.github.io/learningdays-resources/Slides/Examples/power-santiago.pdf)


## Ressources

### Guide des méthodes EGAP

 - Guide des méthodes EGAP [10 choses à savoir sur la puissance statistique](https://egap.org/resource/10-things-you-need-know-about-statistical-power/)

 - Guide des méthodes EGAP [10 choses à savoir sur l'ajustement des covariables](https://egap.org/resource/10-things-to-know-about-covariate-adjustment/)
 
 - Guide des méthodes EGAP [10 choses que vos résulats nuls peuvent signifier](https://egap.org/resource/10-things-your-null-result-might-mean/)

### Notes d'orientation des politiques publiques EGAP et plans de pré-analyse

Quelques exemples d'analyse de puissance statistique dans les conceptions de recherche :

 - [Plan de pré-analyse. La responsabilisation peut transformer la santé : une réplication et une extension de Bjorkman et Svensson (2009)](https://osf.io/qxwmu/)
 
 - [Note d'orientation des politiques publiques EGAP 58 : La responsabilisation bottom-up peut-elle améliorer les perspectives en matière de santé ?](https://egap.org/resource/does-bottom-up-accountability-work-evidence-from-uganda/)


### Outils
 - Analyse de puissance statistique interactive
 
      - [Calculateur de puissance statistique EGAP](https://egap.shinyapps.io/power-app/)
 
      - [rpsychologist](https://rpsychologist.com/d3/NHST/)

 - Packages en R pour l'analyse de puissance statistique
 
      - [pwr](https://cran.r-project.org/web/packages/pwr/index.html)
 
      - [DeclareDesign](https://cran.r-project.org/web/packages/DeclareDesign/index.html), voir aussi <https://declaredesign.org/>

