# Menaces pesant sur la validité interne des expériences aléatoires {.tabset}

Les expériences randomisées peuvent se heurter à des problèmes qui compromettent leur capacité à démontrer les effets causaux, c'est-à-dire menacer leur validité interne. Certaines unités peuvent être exclues des résultats et cette absence peut être due au traitement : soit les unités n'ont pas reçu le traitement qui leur était attribué ou elles ont subi des effets de débordement d'un voisin traité.

Dans ce module, nous abordons certaines menaces courantes et les bonnes pratiques pour les éviter ou les contourner.

## Contenu {.tabset}

 - Passez en revue les trois hypothèses de base discutées dans [l'inférence causale](causal-inference.html) module.

 - Nous avons dit "analysez en randomisant" dans le module sur les [estimandes et estimateurs](estimands-and-estimators.html). N'oubliez pas que vous avez randomisé **l'assignation** du traitement. Vous n'avez pas randomisé si le traitement est reçu, ni si une unité participe à la collecte de données.

 - **Les données manquantes dans les résultats (i.e. l'attrition)** sont particulièrement problématiques si le pattern des données absentes est causé par le traitement lui-même. C'est un problème très courant.

     - Ne supprimez pas les observations de votre analyse pour lesquelles il manque des données.

     - Vous pourriez **borner** les estimations des effets du traitement.

 - **Non-conformité**. L'effet de l'assignation du traitement n'est pas le même que l'effet du traitement reçu. Parfois, les unités ne se conformeront pas au choix de traitement qui leur a été assigné.

     - La conformité unilatérale signifie que certaines unités assignées au traitement ne prennent pas le traitement, et toutes les unités assignées au contrôle ne prennent pas le traitement.
     
     - L'effet moyen local du traitement (local average treamtent effect, LATE), aussi connu sous le nom d’effet causal moyen pour ceux qui se conforment au traitement (complier average causal effect, CACE), est l'effet moyen pour les unités qui prennent le traitement lorsqu'elles sont assignées au traitement. Si l'hypothèse de monotonie et la restriction d'exclusion sont remplies, il est possible d'estimer l'effet moyen local du traitement en cas de non-conformité.

 - **Les "effets de débordement" ou les interférences entre unités** constituent une violation de l'une des hypothèses fondamentales de l'[inférence causale](causalinference.html).

      - Cependant, cela peut ne pas être un problème si vous êtes intéressé par les effets de débordement et/ou si vous avez conçu votre recherche en le prenant tenant en compte.

 - **L'effet Hawthorne** se produit lorsque les sujets se comportent différemment parce qu'ils sont observés.

- **La non-exclusion**. Traiter différemment les unités des groupes de traitement et de contrôle, par exemple avec des processus de collecte de données différents ou une attention particulière pour les unités traitées, peut perturber l'interprétation des résultats expérimentaux.

     - Si l'effet Hawthorne est présent pour le groupe de traitement mais pas pour le groupe de contrôle, il y a une violation de l'hypothèse d'exclusion.



## Slides

Vous trouverez ci-dessous des slides avec le contenu de base de notre conférence sur les menaces à la validité interne des expériences aléatoires. Vous pouvez les utiliser directement ou les copier localement avant de les éditer.

 - [Code source en R Markdown](https://egap.github.io/learningdays-resources/Slides/threats-slides.Rmd)

 - [Version PDF](https://egap.github.io/learningdays-resources/Slides/threats-slides.pdf)

 - [Version HTML](https://egap.github.io/learningdays-resources/Slides/threats-slides.html)

Vous pouvez également voir les slides utilisées lors des précédents EGAP Learning Days :

- [Présentation des menaces aux EGAP Learning Days à l'African School of Economics, Abomey-Calavi, juin 2019 (la première section passe en revue les différents designs de randomisation)](https://egap.github.io/learningdays-resources/Slides/Examples/threats-benin.pdf)

- [Présentation sur l'attrition et les données manquantes aux EGAP Learning Days à l'Universidad Diego Portales à Santiago, Chili, mai 2016](https://egap.github.io/learningdays-resources/Slides/Examples/threats-santiago.pdf)

## Ressources

### Guide des méthodes EGAP

- Guide des méthodes EGAP [10 choses à savoir sur les données manquantes](https://egap.org/resource/10-things-to-know-about-missing-data/)

- Guide des méthodes EGAP [Les 10 types d'effets de traitement à connaître](https://egap.org/resource/10-types-of-treatment-effect-you-should-know-about/)

- Guide des méthodes EGAP [10 choses à savoir sur l'effet moyen local du traitement](https://egap.org/resource/10-things-to-know-about-the-local-average-treatment-effect/)

### Livres, chapitres et articles

- [Procédures opérationnelles standard pour le laboratoire de Don Green à l'Université de Columbia](https://github.com/acoppock/Green-Lab-SOP). Un ensemble complet de procédures et de règles de base pour mener des études expérimentales.
- [@gerber_field_2012]. Chapitres 5 à 8 traitent de non-conformité, d'attrition et d'interférence.

### Note d'orientation des politiques publiques EGAP

- [Note d'orientation EGAP 11 : Observateurs électoraux et fraude au Ghana ](https://egap.org/resource/brief-11-election-observers-and-fraud-in-ghana/)

- [Note d'orientation EGAP 16 : Effets de débordement des observateurs électoraux au Ghana](https://egap.org/resource/brief-16-spillover-effects-of-observers-in-ghana/)
